# Dockerfile
# download java:8 prebuild
FROM   pdoviet/oracle-java:8
# add your mantainer
MAINTAINER  Phuong Do <dovietphuong.ptit@gmail.com>
# copy your application to docker images
ADD bin/monitor-agent /bin/
